apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rhyolite-host-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.rhyolite.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rhyolite-api
            port:
              number: 8000
  - host: webui.rhyolite.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rhyolite-webui
            port:
              number: 10000