apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - seed-job.yaml
  - api.yaml
  - cors-config.yaml
  - test-job.yaml
  - webui.yaml
  - ingress.yaml
images:
  - name: rhyolite-api
    newName: eyecanai/rhyolite-api
    newTag: 139dac2314bdf51e6ac1a76ecf58b71952b6142e
  - name: rhyolite-seed
    newName: eyecanai/rhyolite-seed
    newTag: 139dac2314bdf51e6ac1a76ecf58b71952b6142e
  - name: rhyolite-webui
    newName: eyecanai/rhyolite-webui
    newTag: 30afebb91715be4877a6fe34b23d304fe716e04f
  - name: rhyolite-test
    newName: eyecanai/rhyolite-test
    newTag: 139dac2314bdf51e6ac1a76ecf58b71952b6142e
