apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - seed-job.yaml
  - api.yaml
  - cors-config.yaml
  - test-job.yaml
  - webui.yaml
  - ingress.yaml
images:
  - name: rhyolite-api
    newName: eyecanai/rhyolite-api
    newTag: 7b9da524be1c63e2513163ad3229515b1367bcfe
  - name: rhyolite-seed
    newName: eyecanai/rhyolite-seed
    newTag: 7b9da524be1c63e2513163ad3229515b1367bcfe
  - name: rhyolite-webui
    newName: eyecanai/rhyolite-webui
    newTag: a4b34d542fcf451dd85ac18390c297a63c68c8e8
