apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - seed-job.yaml
  - api.yaml
  - cors-config.yaml
  - test-job.yaml
  - webui.yaml
  - ingress.yaml
images:
  - name: rhyolite-api
    newName: eyecanai/rhyolite-api
    newTag: b2b7a7819292704c9ed05c8253287da019d62559
  - name: rhyolite-seed
    newName: eyecanai/rhyolite-seed
    newTag: b2b7a7819292704c9ed05c8253287da019d62559
  - name: rhyolite-webui
    newName: eyecanai/rhyolite-webui
    newTag: b9bc9c70e952abf5335f9ff99b6da5bae0ec1fb3
  - name: rhyolite-test
    newName: eyecanai/rhyolite-test
    newTag: b2b7a7819292704c9ed05c8253287da019d62559
